### ISSUE TITLE
V not adding after ghost

### ISSUE THREAD

**Issue by ghost** [IRC4Fun/voiceallbut#7]
Having V not add to vab list if Nickserv GHOST command is used.

**Comment by siniStar7** [comment]
v (voiceallbut) does not VAB during ghosts being killed by NickServ, but if you kill the client yourself, you have qualified your client for an AUTO VAB.

> ⇐ @Ka quit (~Ka@IRC4Fun/staff/Karion) Killed (User35735 (ghost))
> 6:14:16 AM 
> <@v> @Ops *** [auto] VAB: Flags for Ka(Ka) are now: h|V

If you had used NickServ to GHOST the client _(NickServ GHOST KILLs are excluded from auto-VABs)_, then the client would not have been VAB'd.

This functionality was added in April, 2017 via commit 333634bc3461f6d0e7ceaf7638a85a172c70a14e
